### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by eychenz** [gisce/locust-xmlrpc#6]
Currently installation of `locust-xmlrpc` fails due to the locust project moving from `locustio` to `locust` namespace in pypi.
According to https://github.com/locustio/locust/issues/817 ,
`Locust package has moved from 'locustio' to 'locust'. Please update your reference`.

minor change in `setup.py` can help fixing the issue.
```
-        'locustio',
+        'locust',
```

**Comment by eychenz** [comment]
@ecarreras Could you please take a look at :point_up: ?

**Comment by ecarreras** [comment]
Thank you sou much
